version: "3.9"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=jokes_app
    ports:
      - "5432:5432"
  web:
    build: .
    command: bash -c "alembic upgrade head && uvicorn jokes_app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    depends_on:
      - db
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db