"""First migration

Revision ID: e0215f626b86
Revises: 
Create Date: 2022-01-02 11:49:06.389752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0215f626b86'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jokes",
        sa.Column("id", sa.Integer, primary_key=True, index=True),
        sa.Column("jokes", sa.String)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("jokes")
    # ### end Alembic commands ###
